var animalData = {
	ar: {
		name: 'Arapaima',
		scName: 'Arapaima gigas',
		type: 'Fish',
		diet: 'Carnivores',
		age: '15 to 20 years',
		size: 'up to 14.76 ft',
		weight: 'up to 440 lbs',
	},
	ca: {
		name: 'Capybara',
		scName: 'Hydrochoerus hydrochaeris',
		type: 'Mammals',
		diet: 'Herbnivores',
		age: '8 to 10 years',
		size: '39 in to 51 in',
		weight: '66 lb to 154 lb lbs',
	},
	fl: {
		name: 'Flamnigo',
		scName: 'Phoenicopterus',
		type: 'Birds',
		diet: 'Omnivores',
		age: '15 to 30 years',
		size: '39 in to 59 in, wingspan 59 in to 71 in',
		weight: '4.4 lb to 8.8 lb lbs',
	},
	
	ga: {
		name: 'Giant Anteater',
		scName: 'Myremecophaga tridactyla',
		type: 'Mammals',
		diet: 'Carnivores',
		age: 'Average life in The Wild: 14 years',
		size: 'Head and body, 6 to 7.1 ft',
		weight: '40 to 140 lbs',
	},
	go: {
		name: 'Giant Otter',
		scName: 'Pteronura brasiliensis',
		type: 'Mammals',
		diet: 'Carnivores',
		age: 'In the Wild 12 years, captivity 21 years',
		size: 'Up to 6 ft',
		weight: '75 lb',
	},
	ha: {
		name: 'Hamster',
		scName: 'Mesocricetus Auratus',
		type: 'Mammals',
		diet: 'Omnivores',
		age: '2 to 3 years',
		size: '2 to 11 in',
		weight: '3.5 to 32oz',
	},
	hb: {
		name: 'Humming Bird',
		scName: 'Trochilidae',
		type: 'Birds',
		diet: 'Omnivores',
		age: '3 to 5 years',
		size: 'Wing span 2in to 8in',
		weight: '0.07oz to 0.7oz',
	},
	he: {
		name: 'American Harpy Eagle',
		scName: 'Thrasaetus harpyia',
		type: 'Birds',
		diet: 'Carnivores',
		age: '25 to 35 years',
		size: 'Wing span 6.5 ft, length 3.2 ft,',
		weight: 'Male 9 to 11 lbs, Female 13 to 20 lbs',
	},
	hm: {
		name: 'Howler Monkey',
		scName: 'Alouatta',
		type: 'Mammals',
		diet: 'Omnivores',
		age: '15 to 20 years',
		size: '22 to 36 inches',
		weight: '6.6 to 20lbs',
	},
	jg: {
		name: 'Jaguar',
		scName: 'Panthera onca',
		type: 'Mammals',
		diet: 'Carnivores',
		age: '12 to 15 years',
		size: '5 to 6 ft,',
		weight: '100 to 250 lbs',
	},
	kf: {
		name: 'King Fisher',
		scName: 'Coraciiformes',
		type: 'Birds',
		diet: 'Omnivores',
		age: '6 to 10 years',
		size: '11.8 to 39.5 in',
		weight: '0.4oz to 6oz',
	},
	mc: {
		name: 'Macaw',
		scName: 'Psittacidae',
		type: 'Birds',
		diet: 'Omnivores',
		age: 'Avg life in wild up to 60 years',
		size: '11.8 to 39.5 inches',
		weight: '4.5 to 3.75 lbs',
	},
	ml: {
		name: 'Puma/Mountain Lion',
		scName: 'puma (Felis) Concolor',
		type: 'Mammals',
		diet: 'Carnivores',
		age: '10 to 20 years',
		size: '5-9 ft,',
		weight: '64 to 198 lbs',
	},
	oc: {
		name: 'Ocelot/Painted Leopard',
		scName: 'Leopardus pardalis',
		type: 'Mammals',
		diet: 'Carnivores',
		age: 'Up to 20 years',
		size: '22in to 40in,',
		weight: '25 to 35 lbs',
	},
	pa: {
		name: 'Panther, Black Jaguar',
		scName: 'Panthera pardus, Panthera onca',
		type: 'Mammals',
		diet: 'Carnivores',
		age: '12 to 15 years',
		size: 'Nose to tail, 5.9 to 7.9 ft',
		weight: '125 to 220 lbs',
	},
	pr: {
		name: 'Parrot',
		scName: 'Psittaciformes',
		type: 'Birds',
		diet: 'Omnivores',
		age: 'Avg life in wild up to 80 years',
		size: '3.5 to 40 in',
		weight: '2.25 oz to 3.5 lbs',
	},
	tp: {
		name: 'Tapir',
		scName: 'Tapiridae',
		type: 'Mammals',
		diet: 'Omnivores',
		age: 'Avg life in wild 25 to 30 years',
		size: 'Shoulder height 29 to 42 in',
		weight: '500 to 800 lb',
	},
	tt: {
		name: 'Toco Toucan',
		scName: 'Ramphastos toco',
		type: 'Birds',
		diet: 'Omnivores',
		age: 'Avg life in wild up to 20 years',
		size: 'Body 24 in, bill 7.5 in',
		weight: '20 oz',
	},
	si: {
		name: 'Scarlet Ibis',
		scName: 'Eudocimus ruber',
		type: 'Birds',
		diet: 'Carnivores',
		age: '15 years',
		size: '2.2 ft',
		weight: '1.4 lb',
	},
	sk: {
		name: 'Snail Kite Karen',
		scName: 'Rostrhamus sociabilis',
		type: 'Birds',
		diet: 'Carnivores',
		age: '9.5 years',
		size: 'Body lenght 15 to 18 in, wingspan 4 ft',
		weight: '12 to 14 oz',
	},
	sl: {
		name: 'Sloth',
		scName: 'Choloepus Hoffmani',
		type: 'Mammals',
		diet: 'Omnivores',
		age: '25 to 40 years',
		size: '20 to 28in',
		weight: '10-13lbs',
	},
	sm: {
		name: 'Sakiwinki/Sqirrel Monkey',
		scName: 'Saimiri sciureus',
		type: 'Mammals',
		diet: 'Carnivores',
		age: '15 to 20 years',
		size: '9.8 to 14in',
		weight: '1.7lbs to 2.4lbs',
	}
};